# OLLAMA
ollama.url=http://localhost:11434/api/generate
ollama.model=llama3
#ollama.translation.model=alia-translation
ollama.translation.model=qwen2.5:7b

# APP
spring.application.name=smartdoc

# Perfil activo
spring.profiles.active=local